# -*- coding: utf-8 -*-
# 全角ひらがな => 半角カタカナ
Kana::Converter::HIRAGANA = Hash[*{# 記号
                                   0x3001 => 0xFF64,
                                   0x3002 => 0xFF61,
                                   0x300C => 0xFF62,
                                   0x300D => 0xFF63,
                                   0x309B => 0xFF9E,
                                   0x309C => 0xFF9F,
                                   0x30FB => 0xFF65,
                                   0x30FC => 0xFF70,
                                   0x309B => 0xFF9E,
                                   # 清音
                                   0x3041 => 0xFF67, # HIRAGANA LETTER SMALL A
                                   0x3042 => 0xFF71, # HIRAGANA LETTER A
                                   0x3043 => 0xFF68, # HIRAGANA LETTER SMALL I
                                   0x3044 => 0xFF72, # HIRAGANA LETTER I
                                   0x3045 => 0xFF69, # HIRAGANA LETTER SMALL U
                                   0x3046 => 0xFF73, # HIRAGANA LETTER U
                                   0x3047 => 0xFF6A, # HIRAGANA LETTER SMALL E
                                   0x3048 => 0xFF74, # HIRAGANA LETTER E
                                   0x3049 => 0xFF6B, # HIRAGANA LETTER SMALL O
                                   0x304A => 0xFF75, # HIRAGANA LETTER O
                                   0x304B => 0xFF76, # HIRAGANA LETTER KA
                                   0x304D => 0xFF77, # HIRAGANA LETTER KI
                                   0x304F => 0xFF78, # HIRAGANA LETTER KU
                                   0x3051 => 0xFF79, # HIRAGANA LETTER KE
                                   0x3053 => 0xFF7A, # HIRAGANA LETTER KO
                                   0x3055 => 0xFF7B, # HIRAGANA LETTER SA
                                   0x3057 => 0xFF7C, # HIRAGANA LETTER SI
                                   0x3059 => 0xFF7D, # HIRAGANA LETTER SU
                                   0x305B => 0xFF7E, # HIRAGANA LETTER SE
                                   0x305D => 0xFF7F, # HIRAGANA LETTER SO
                                   0x305F => 0xFF80, # HIRAGANA LETTER TA
                                   0x3061 => 0xFF81, # HIRAGANA LETTER TI
                                   0x3063 => 0xFF6F, # HIRAGANA LETTER SMALL TU
                                   0x3064 => 0xFF82, # HIRAGANA LETTER TU
                                   0x3066 => 0xFF83, # HIRAGANA LETTER TE
                                   0x3068 => 0xFF84, # HIRAGANA LETTER TO
                                   0x306A => 0xFF85, # HIRAGANA LETTER NA
                                   0x306B => 0xFF86, # HIRAGANA LETTER NI
                                   0x306C => 0xFF87, # HIRAGANA LETTER NU
                                   0x306D => 0xFF88, # HIRAGANA LETTER NE
                                   0x306E => 0xFF89, # HIRAGANA LETTER NO
                                   0x306F => 0xFF8A, # HIRAGANA LETTER HA
                                   0x3072 => 0xFF8B, # HIRAGANA LETTER HI
                                   0x3075 => 0xFF8C, # HIRAGANA LETTER HU
                                   0x3078 => 0xFF8D, # HIRAGANA LETTER HE
                                   0x307B => 0xFF8E, # HIRAGANA LETTER HO
                                   0x307E => 0xFF8F, # HIRAGANA LETTER MA
                                   0x307F => 0xFF90, # HIRAGANA LETTER MI
                                   0x3080 => 0xFF91, # HIRAGANA LETTER MU
                                   0x3081 => 0xFF92, # HIRAGANA LETTER ME
                                   0x3082 => 0xFF93, # HIRAGANA LETTER MO
                                   0x3083 => 0xFF6C, # HIRAGANA LETTER SMALL YA
                                   0x3084 => 0xFF94, # HIRAGANA LETTER YA
                                   0x3085 => 0xFF6D, # HIRAGANA LETTER SMALL YU
                                   0x3086 => 0xFF95, # HIRAGANA LETTER YU
                                   0x3087 => 0xFF6E, # HIRAGANA LETTER SMALL YO
                                   0x3088 => 0xFF96, # HIRAGANA LETTER YO
                                   0x3089 => 0xFF97, # HIRAGANA LETTER RA
                                   0x308A => 0xFF98, # HIRAGANA LETTER RI
                                   0x308B => 0xFF99, # HIRAGANA LETTER RU
                                   0x308C => 0xFF9A, # HIRAGANA LETTER RE
                                   0x308D => 0xFF9B, # HIRAGANA LETTER RO
                                   0x308E => 0xFF9C,
                                   0x308F => 0xFF9C,
                                   0x3090 => 0xFF72,
                                   0x3091 => 0xFF74,
                                   0x3092 => 0xFF66, # HIRAGANA LETTER WO
                                   0x3093 => 0xFF9D, # HIRAGANA LETTER N
                                 }.map{ |k,v| [[k].pack('U'), [v].pack('U')] }.flatten]

# 全角ひらがな => 半角カタカナ
Kana::Converter::HIRAGANA_DAKUON = Hash[*{# 濁音
                                          0x304C => [0xFF76,0xFF9E], # HIRAGANA LETTER GA
                                          0x304E => [0xFF77,0xFF9E], # HIRAGANA LETTER GI
                                          0x3050 => [0xFF78,0xFF9E], # HIRAGANA LETTER GU
                                          0x3052 => [0xFF79,0xFF9E], # HIRAGANA LETTER GE
                                          0x3054 => [0xFF7A,0xFF9E], # HIRAGANA LETTER GO
                                          0x3056 => [0xFF7B,0xFF9E], # HIRAGANA LETTER ZA
                                          0x3058 => [0xFF7C,0xFF9E], # HIRAGANA LETTER ZI
                                          0x305A => [0xFF7D,0xFF9E], # HIRAGANA LETTER ZU
                                          0x305C => [0xFF7E,0xFF9E], # HIRAGANA LETTER ZE
                                          0x305E => [0xFF7F,0xFF9E], # HIRAGANA LETTER ZO
                                          0x3060 => [0xFF80,0xFF9E], # HIRAGANA LETTER DA
                                          0x3062 => [0xFF81,0xFF9E], # HIRAGANA LETTER DI
                                          0x3065 => [0xFF82,0xFF9E], # HIRAGANA LETTER DU
                                          0x3067 => [0xFF83,0xFF9E], # HIRAGANA LETTER DE
                                          0x3069 => [0xFF84,0xFF9E], # HIRAGANA LETTER DO
                                          0x3070 => [0xFF8A,0xFF9E], # HIRAGANA LETTER BA
                                          0x3073 => [0xFF8B,0xFF9E], # HIRAGANA LETTER BI
                                          0x3076 => [0xFF8C,0xFF9E], # HIRAGANA LETTER BU
                                          0x3079 => [0xFF8D,0xFF9E], # HIRAGANA LETTER BE
                                          0x307C => [0xFF8E,0xFF9E], # HIRAGANA LETTER BO
                                          # 半濁音
                                          0x3071 => [0xFF8A,0xFF9F], # HIRAGANA LETTER PA
                                          0x3074 => [0xFF8B,0xFF9F], # HIRAGANA LETTER PI
                                          0x3077 => [0xFF8C,0xFF9F], # HIRAGANA LETTER PU
                                          0x307A => [0xFF8D,0xFF9F], # HIRAGANA LETTER PE
                                          0x307D => [0xFF8E,0xFF9F], # HIRAGANA LETTER PO
                                        }.map{ |k,v| [[k].pack('U'), v.map{ |e| [e].pack('U') }.join ] }.flatten]

Kana::Converter::HIRAGANA_INVERT = Hash[*{
                                          0xFF72 => 0x3044,
                                        }.map{ |k,v| [[k].pack('U'), [v].pack('U')] }.flatten]
